-- Seeda yahoo_ticker för alla 68 NGM-bolag
-- Kör denna i Supabase SQL Editor EFTER 20260309_stock_prices.sql

UPDATE companies SET yahoo_ticker = 'ABIG.ST'      WHERE ticker = 'ABIG';
UPDATE companies SET yahoo_ticker = 'ADVT.ST'      WHERE ticker = 'ADVT';
UPDATE companies SET yahoo_ticker = 'AFRI.ST'      WHERE ticker = 'AFRI';
UPDATE companies SET yahoo_ticker = 'ARBO-A.ST'    WHERE ticker = 'ARBO-A' OR ticker = 'ARBO';
UPDATE companies SET yahoo_ticker = 'ATANA.ST'     WHERE ticker = 'ATANA';
UPDATE companies SET yahoo_ticker = 'AVSALT.ST'    WHERE ticker = 'AVSALT';
UPDATE companies SET yahoo_ticker = 'BLUE.ST'      WHERE ticker = 'BLUE';
UPDATE companies SET yahoo_ticker = 'BRIX.ST'      WHERE ticker = 'BRIX';
UPDATE companies SET yahoo_ticker = 'CARDEO.ST'    WHERE ticker = 'CARDEO';
UPDATE companies SET yahoo_ticker = 'COEGIN.ST'    WHERE ticker = 'COEGIN';
UPDATE companies SET yahoo_ticker = 'CRET.ST'      WHERE ticker = 'CRET';
UPDATE companies SET yahoo_ticker = 'CRWN.ST'      WHERE ticker = 'CRWN';
UPDATE companies SET yahoo_ticker = 'DIAH.ST'      WHERE ticker = 'DIAH';
UPDATE companies SET yahoo_ticker = 'DIV-B.ST'     WHERE ticker = 'DIV-B' OR ticker = 'DIV';
UPDATE companies SET yahoo_ticker = 'ECC-B.ST'     WHERE ticker = 'ECC-B' OR ticker = 'ECC';
UPDATE companies SET yahoo_ticker = 'EMART.ST'     WHERE ticker = 'EMART';
UPDATE companies SET yahoo_ticker = 'ENRAD.ST'     WHERE ticker = 'ENRAD';
UPDATE companies SET yahoo_ticker = 'BAT.ST'       WHERE ticker = 'BAT';
UPDATE companies SET yahoo_ticker = 'F2M.ST'       WHERE ticker = 'F2M';
UPDATE companies SET yahoo_ticker = 'FRNT-B.ST'    WHERE ticker = 'FRNT-B' OR ticker = 'FRNT';
UPDATE companies SET yahoo_ticker = 'THRILL.ST'    WHERE ticker = 'THRILL';
UPDATE companies SET yahoo_ticker = 'GARPCO-B.ST'  WHERE ticker = 'GARPCO-B' OR ticker = 'GARPCO';
UPDATE companies SET yahoo_ticker = 'GTG.ST'       WHERE ticker = 'GTG';
UPDATE companies SET yahoo_ticker = 'BTCX.ST'      WHERE ticker = 'BTCX';
UPDATE companies SET yahoo_ticker = 'GMERC-B.ST'   WHERE ticker = 'GMERC-B' OR ticker = 'GMERC';
UPDATE companies SET yahoo_ticker = 'H100.ST'      WHERE ticker = 'H100';
UPDATE companies SET yahoo_ticker = 'HMPLY.ST'     WHERE ticker = 'HMPLY';
UPDATE companies SET yahoo_ticker = 'HYCO.ST'      WHERE ticker = 'HYCO';
UPDATE companies SET yahoo_ticker = 'INFRA.ST'     WHERE ticker = 'INFRA';
UPDATE companies SET yahoo_ticker = 'JDT.ST'       WHERE ticker = 'JDT';
UPDATE companies SET yahoo_ticker = 'GATE.ST'      WHERE ticker = 'GATE';
UPDATE companies SET yahoo_ticker = 'KOBR-B.ST'    WHERE ticker = 'KOBR-B' OR ticker = 'KOBR';
UPDATE companies SET yahoo_ticker = 'KVIX.ST'      WHERE ticker = 'KVIX';
UPDATE companies SET yahoo_ticker = 'LATF-B.ST'    WHERE ticker = 'LATF-B' OR ticker = 'LATF';
UPDATE companies SET yahoo_ticker = 'LEVBIO.ST'    WHERE ticker = 'LEVBIO';
UPDATE companies SET yahoo_ticker = 'LAIR.ST'      WHERE ticker = 'LAIR';
UPDATE companies SET yahoo_ticker = 'LINKAB.ST'    WHERE ticker = 'LINKAB';
UPDATE companies SET yahoo_ticker = 'LOHILO.ST'    WHERE ticker = 'LOHILO';
UPDATE companies SET yahoo_ticker = 'LUMITO.ST'    WHERE ticker = 'LUMITO';
UPDATE companies SET yahoo_ticker = 'MAHVIE.ST'    WHERE ticker = 'MAHVIE';
UPDATE companies SET yahoo_ticker = 'MCLR.ST'      WHERE ticker = 'MCLR';
UPDATE companies SET yahoo_ticker = 'MEGR.ST'      WHERE ticker = 'MEGR';
UPDATE companies SET yahoo_ticker = 'NXAR.ST'      WHERE ticker = 'NXAR';
UPDATE companies SET yahoo_ticker = 'NGS.ST'       WHERE ticker = 'NGS';
UPDATE companies SET yahoo_ticker = 'NIUTEC.ST'    WHERE ticker = 'NIUTEC';
UPDATE companies SET yahoo_ticker = 'NODE.ST'      WHERE ticker = 'NODE';
UPDATE companies SET yahoo_ticker = 'NORDIG.ST'    WHERE ticker = 'NORDIG';
UPDATE companies SET yahoo_ticker = 'CAPS.ST'      WHERE ticker = 'CAPS';
UPDATE companies SET yahoo_ticker = 'NOSIUM-B.ST'  WHERE ticker = 'NOSIUM-B' OR ticker = 'NOSIUM';
UPDATE companies SET yahoo_ticker = 'NOWO.ST'      WHERE ticker = 'NOWO';
UPDATE companies SET yahoo_ticker = 'PIXEL.ST'     WHERE ticker = 'PIXEL';
UPDATE companies SET yahoo_ticker = 'PIXFAM.ST'    WHERE ticker = 'PIXFAM';
UPDATE companies SET yahoo_ticker = 'POLYMER.ST'   WHERE ticker = 'POLYMER';
UPDATE companies SET yahoo_ticker = 'PHYR-B.ST'    WHERE ticker = 'PHYR-B' OR ticker = 'PHYR';
UPDATE companies SET yahoo_ticker = 'PRLD.ST'      WHERE ticker = 'PRLD';
UPDATE companies SET yahoo_ticker = 'QBRICK.ST'    WHERE ticker = 'QBRICK';
UPDATE companies SET yahoo_ticker = 'RMDX.ST'      WHERE ticker = 'RMDX';
UPDATE companies SET yahoo_ticker = 'RLOS-B.ST'    WHERE ticker = 'RLOS-B' OR ticker = 'RLOS';
UPDATE companies SET yahoo_ticker = 'REAL.ST'      WHERE ticker = 'REAL';
UPDATE companies SET yahoo_ticker = 'RLVNC.ST'     WHERE ticker = 'RLVNC';
UPDATE companies SET yahoo_ticker = 'RENT.ST'      WHERE ticker = 'RENT';
UPDATE companies SET yahoo_ticker = 'SLG-B.ST'     WHERE ticker = 'SLG-B' OR ticker = 'SLG';
UPDATE companies SET yahoo_ticker = 'SARS.ST'      WHERE ticker = 'SARS';
UPDATE companies SET yahoo_ticker = 'SDS.ST'       WHERE ticker = 'SDS';
UPDATE companies SET yahoo_ticker = 'SEHED-B.ST'   WHERE ticker = 'SEHED-B' OR ticker = 'SEHED';
UPDATE companies SET yahoo_ticker = 'STVA-B.ST'    WHERE ticker = 'STVA-B' OR ticker = 'STVA';
UPDATE companies SET yahoo_ticker = 'SBG.ST'       WHERE ticker = 'SBG';
UPDATE companies SET yahoo_ticker = 'SENS.ST'      WHERE ticker = 'SENS';
UPDATE companies SET yahoo_ticker = 'TCC-A.ST'     WHERE ticker = 'TCC-A' OR ticker = 'TCC';
UPDATE companies SET yahoo_ticker = 'THINC.ST'     WHERE ticker = 'THINC';
UPDATE companies SET yahoo_ticker = 'TPGR.ST'      WHERE ticker = 'TPGR';
UPDATE companies SET yahoo_ticker = 'TRML.ST'      WHERE ticker = 'TRML';
UPDATE companies SET yahoo_ticker = 'TRNSF.ST'     WHERE ticker = 'TRNSF';
UPDATE companies SET yahoo_ticker = 'TIRO.ST'      WHERE ticker = 'TIRO';
UPDATE companies SET yahoo_ticker = 'TRIONA.ST'    WHERE ticker = 'TRIONA';

-- Verifiera
SELECT ticker, yahoo_ticker FROM companies WHERE yahoo_ticker IS NOT NULL ORDER BY ticker;
